In [1]:
#importing libraries dataset
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   int64  
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 200.6 KB


In [6]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [7]:
df.Gender.value_counts()

1    5000
0    3555
Name: Gender, dtype: int64

# Step 01 - Regression

In [8]:
#Seperate X,y
x = df.drop('Weight', axis=1)
y = df[['Weight']]

In [9]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [10]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.3, random_state=1)

In [13]:
xtrain.head()

Gender     Height
1277       1  72.385301
5361       0  60.960147
5728       0  69.119292
4276       1  68.271050
3112       1  64.991405

In [14]:
xtest.head()

Gender     Height
7154       0  65.068038
3258       1  70.824643
2188       1  68.663594
5609       0  65.987610
3186       1  70.901461

In [15]:
xtrain.shape

(5988, 2)

In [16]:
ytrain.shape

(5988, 1)

In [17]:
xtest.shape

(2567, 2)

In [18]:
ytest.shape

(2567, 1)

In [19]:
ytest.head()

Weight
7154  160.800726
3258  184.516688
2188  184.262796
5609  166.844114
3186  200.466282

In [20]:
ytrain.head()

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

In [21]:
from sklearn.linear_model import LinearRegression  #linear regression

In [22]:
lr1= LinearRegression()

In [23]:
lr1.fit(xtrain,ytrain)

LinearRegression()

In [24]:
m=lr1.coef_
m

array([[19.34359322,  5.96887438]])

In [25]:
c= lr1.intercept_
c

array([-244.55280903])

In [26]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [27]:
mse= mean_squared_error(ytest, lr1.predict(xtest)) 

In [28]:
mse        #mean squared error for linear regression is 99.6725

99.67250998070031

In [29]:
lr1.score(xtest, ytest)  #testing accuracy 90.59 percent

0.905995960709116

In [30]:
lr1.score(xtrain,ytrain) #training accuracy 89.72 percent


0.8972135459668118

In [31]:
from sklearn.neighbors import KNeighborsRegressor #Knn regressor

In [32]:
knr1= KNeighborsRegressor()

In [33]:
knr1.fit(xtrain,ytrain)

KNeighborsRegressor()

In [34]:
knr1.score(xtrain,ytrain) #training accuracy 91.7 percent

0.9170756955071054

In [35]:
knr1.score(xtest,ytest) #testing accuracy 88.38 percent 

0.8838502073708883

# Step 02 - Classification

In [36]:
x = df.drop('Gender', axis=1)
y = df[['Gender']]

In [37]:
y.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [38]:
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size= 0.3, random_state=1)

In [41]:
xtrain.head()

Height      Weight
1277  72.385301  189.165592
5361  60.960147  124.876796
5728  69.119292  168.864403
4276  68.271050  172.941248
3112  64.991405  144.551044

In [42]:
ytrain.head()

Gender
1277       1
5361       0
5728       0
4276       1
3112       1

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
knc=KNeighborsClassifier()

In [45]:
knc.fit(xtrain,ytrain)

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [46]:
knc.score(xtest,ytest) #testing accuracy 91.46 percent

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9146864043630697

In [47]:
knc.score(xtrain,ytrain) #training accuracy 92.63 percent

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9263527054108216

In [48]:
knc.predict([[72.385301,241.893563]]) #result 1 which means the gender is male

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1], dtype=int64)